### ISSUE TITLE
About the variant of add bond length loss.

### ISSUE THREAD

**Issue by Frankie123421** [pengxingang/MolDiff#1]
Hi, congratulations on your nice work that is to be appear in ICML 2023. I've read it from arxiv and have some problems about the variant of baselines: additionally add bond length loss, as the code is not available now. I wonder if this baseline is based on EDM or the MolDiff you proposed, and in the appendix you mention that minimize the difference between the real bond lengths at $t-1$ with the predicted ones given the coordinates at $t$. However in practice, we do not actually sample $t-1$ and the networks in fact predict the states at $t=0$ given the states at $t=t$. Is this actually implemented by comparing the bond lengths at $t=0$?

**Comment by pengxingang** [comment]
Hi, thanks for your interest in our work. The add-bond-length-loss baseline is based on MolDiff. You are right that we do not sample $t-1$ but use the prediction at $t=0$ when calculating the losses for continuous variables (i.e., the atom positions). The predicted and the ground-truth bond lengths are calculated from the atom positions. So in the implementation, the loss of the bond lengths is calculated at $t=0$.

**Comment by Frankie123421** [comment]
Thanks for your reply.
